/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const AddPointsResult = IDL.Variant({
  'success' : IDL.Nat,
  'pointsUpdateFailed' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'displayName' : IDL.Text,
  'email' : IDL.Text,
  'college' : IDL.Text,
});
export const RankingDetails = IDL.Record({
  'streak' : IDL.Nat,
  'displayName' : IDL.Text,
  'joinDate' : Time,
  'longestStreak' : IDL.Nat,
  'college' : IDL.Opt(IDL.Text),
  'points' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addDailyAttendance' : IDL.Func([Time, IDL.Vec(IDL.Text)], [], []),
  'addPoints' : IDL.Func([IDL.Nat], [AddPointsResult], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'calculateMaxBunkableClasses' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Nat],
      ['query'],
    ),
  'deleteCallerUser' : IDL.Func([], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getGlobalRankingPaginated' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(RankingDetails)],
      ['query'],
    ),
  'getRankingByCollege' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat],
      [IDL.Vec(RankingDetails)],
      ['query'],
    ),
  'getRequiredAttendancePercentage' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setRequiredAttendancePercentage' : IDL.Func([IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const AddPointsResult = IDL.Variant({
    'success' : IDL.Nat,
    'pointsUpdateFailed' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'displayName' : IDL.Text,
    'email' : IDL.Text,
    'college' : IDL.Text,
  });
  const RankingDetails = IDL.Record({
    'streak' : IDL.Nat,
    'displayName' : IDL.Text,
    'joinDate' : Time,
    'longestStreak' : IDL.Nat,
    'college' : IDL.Opt(IDL.Text),
    'points' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addDailyAttendance' : IDL.Func([Time, IDL.Vec(IDL.Text)], [], []),
    'addPoints' : IDL.Func([IDL.Nat], [AddPointsResult], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'calculateMaxBunkableClasses' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Nat],
        ['query'],
      ),
    'deleteCallerUser' : IDL.Func([], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getGlobalRankingPaginated' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(RankingDetails)],
        ['query'],
      ),
    'getRankingByCollege' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat],
        [IDL.Vec(RankingDetails)],
        ['query'],
      ),
    'getRequiredAttendancePercentage' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setRequiredAttendancePercentage' : IDL.Func([IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };