/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const RankingError = IDL.Variant({
  'userNotAuthenticated' : IDL.Null,
  'displayNameUpdateFailed' : IDL.Null,
  'pointsUpdateFailed' : IDL.Null,
});
export const RankingEntry = IDL.Record({
  'displayName' : IDL.Text,
  'points' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addPoints' : IDL.Func([IDL.Text, IDL.Nat], [RankingError], []),
  'getCurrentWeekRanking' : IDL.Func([], [IDL.Vec(RankingEntry)], ['query']),
  'registerDisplayName' : IDL.Func([IDL.Text], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const RankingError = IDL.Variant({
    'userNotAuthenticated' : IDL.Null,
    'displayNameUpdateFailed' : IDL.Null,
    'pointsUpdateFailed' : IDL.Null,
  });
  const RankingEntry = IDL.Record({
    'displayName' : IDL.Text,
    'points' : IDL.Nat,
  });
  
  return IDL.Service({
    'addPoints' : IDL.Func([IDL.Text, IDL.Nat], [RankingError], []),
    'getCurrentWeekRanking' : IDL.Func([], [IDL.Vec(RankingEntry)], ['query']),
    'registerDisplayName' : IDL.Func([IDL.Text], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };