/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AddPointsResult = { 'success' : bigint } |
  { 'pointsUpdateFailed' : null };
export interface RankingDetails {
  'streak' : bigint,
  'displayName' : string,
  'joinDate' : Time,
  'longestStreak' : bigint,
  'college' : [] | [string],
  'points' : bigint,
}
export type Time = bigint;
export interface UserProfile {
  'displayName' : string,
  'email' : string,
  'college' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addDailyAttendance' : ActorMethod<[Time, Array<string>], undefined>,
  'addPoints' : ActorMethod<[bigint], AddPointsResult>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'calculateMaxBunkableClasses' : ActorMethod<[bigint, bigint], bigint>,
  'deleteCallerUser' : ActorMethod<[], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getGlobalRankingPaginated' : ActorMethod<
    [bigint, bigint],
    Array<RankingDetails>
  >,
  'getRankingByCollege' : ActorMethod<
    [string, bigint, bigint],
    Array<RankingDetails>
  >,
  'getRequiredAttendancePercentage' : ActorMethod<[], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setRequiredAttendancePercentage' : ActorMethod<[bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];